CREATE TABLE [etl].[Subscribermail_Customer_Pivot_news]
(
[ETL_CreatedOn] [datetime] NOT NULL,
[ETL_UpdatedOn] [datetime] NOT NULL,
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[email] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientData_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Account Credit] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Number #2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Number #3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Number #4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Rep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Rep email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Rep phone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Blackhawks Bar] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fantasy Team Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite Player (#1)] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite Player (#2)] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite Player (#3)] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite Team] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 010318] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 010518] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 010718] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 010918] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 011018] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 011218] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 011418] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 032218] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 032418] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 032618] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 032918] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 033018] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 040418] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 040618] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 040718] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 122917] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Night Code 123117] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hull Plan 2015] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[In Market] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Password] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Manager] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TixExchange Credit] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic First Seat] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic Last Seat] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic Promo Code] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic Purchase Price] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic Row] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter Classic Section] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YH Team Link] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YH Team Password] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
CREATE NONCLUSTERED INDEX [idx_Pivot_News] ON [etl].[Subscribermail_Customer_Pivot_news] ([RecipientData_id])
GO
